THEME = "/themes/dark-blue.json"
DARK = "dark"
LIGHT = "light"

FONT_NAME = "Roboto"
FONT_SIZE_NORMAL = 20
FONT_SIZE_LARGE = 40
FONT_SIZE_LARGER = 50
FONT_SIZE_XLARGE = 60
FONT_SIZE_XXLARGE = 80

UPDATE_TIME = 500